# Generated by Django 4.1.4 on 2022-12-29 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BerkasPengguna',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAMA_BERKAS', models.TextField(max_length=200)),
                ('JENIS_BERKAS', models.CharField(choices=[('(Dosen) Proposal Penelitian', '(Dosen) Proposal Penelitian'), ('(Dosen) Laporan Akhir Penelitian', '(Dosen) Laporan Akhir Penelitian'), ('(Dosen) Pengabdian pada Masyarakat', '(Dosen) Pengabdian pada Masyarakat'), ('(Mahasiswa) Proposal Skripsi/TA', '(Mahasiswa) Proposal Skripsi/TA'), ('(Mahasiswa) Sidang Skripsi/TA', '(Mahasiswa) Sidang Skripsi/TA'), ('(Umum) Focus Group Discussion', '(Umum) Focus Group Discussion'), ('(Umum) Lainnya', '(Umum) Lainnya')], max_length=100)),
                ('LINK_BERKAS', models.URLField()),
            ],
            options={
                'verbose_name_plural': '01. Berkas Pengguna',
            },
        ),
        migrations.CreateModel(
            name='PengajuanJadwal',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAMA_PRESENTER', models.CharField(max_length=80)),
                ('TGL_PENGAJUAN', models.DateField()),
                ('JENIS_PENGAJUAN', models.CharField(choices=[('(Dosen) Proposal Penelitian', '(Dosen) Proposal Penelitian'), ('(Dosen) Laporan Akhir Penelitian', '(Dosen) Laporan Akhir Penelitian'), ('(Dosen) Pengabdian pada Masyarakat', '(Dosen) Pengabdian pada Masyarakat'), ('(Mahasiswa) Proposal Skripsi/TA', '(Mahasiswa) Proposal Skripsi/TA'), ('(Mahasiswa) Sidang Skripsi/TA', '(Mahasiswa) Sidang Skripsi/TA'), ('(Umum) Focus Group Discussion', '(Umum) Focus Group Discussion'), ('(Umum) Lainnya', '(Umum) Lainnya')], max_length=100)),
                ('JUDUL_BERKAS', models.TextField(max_length=1000)),
                ('SUMBER_PENDANAAN', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External'), ('Hibah', 'Hibah'), ('Lainnya', 'Lainnya')], max_length=25)),
                ('KETERANGAN_PENDANAAN', models.CharField(blank=True, max_length=150)),
                ('NOMINAL_PEMBIAYAAN', models.DecimalField(decimal_places=0, max_digits=13)),
                ('LINK_BERKAS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_jadwal', to='lppm.berkaspengguna')),
            ],
            options={
                'verbose_name_plural': '02. Pengajuan Jadwal',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NIDN_NPM', models.CharField(max_length=13)),
                ('KATEGORI', models.CharField(choices=[('Dosen', 'Dosen'), ('Mahasiswa', 'Mahasiswa'), ('Umum', 'Umum')], max_length=20)),
                ('PEJABAT_LPPM', models.CharField(choices=[('Ketua LPPM', 'Ketua LPPM'), ('Anggota LPPM', 'Anggota LPPM'), ('Tidak', 'Tidak')], max_length=20)),
                ('REVIEWER', models.CharField(choices=[('Ya', 'Ya'), ('Tidak', 'Tidak')], max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '00. Profil Pengguna',
            },
        ),
        migrations.CreateModel(
            name='PengajuanJadwalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TGL_SEMINAR', models.DateField()),
                ('STATUS_PENGAJUAN', models.CharField(choices=[('Dijadwalkan', 'Dijadwalkan'), ('Ditolak', 'Ditolak'), ('Revisi', 'Revisi'), ('Selesai', 'Selesai')], max_length=11)),
                ('KESIMPULAN', models.TextField(blank=True, max_length=1000)),
                ('CATATAN_REVIEWER1', models.TextField(blank=True, max_length=1000)),
                ('CATATAN_REVIEWER2', models.TextField(blank=True, max_length=1000)),
                ('CATATAN_REVIEWER3', models.TextField(blank=True, max_length=1000)),
                ('ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lppm.pengajuanjadwal')),
                ('PEJABAT_LPPM', models.ManyToManyField(limit_choices_to={'PEJABAT_LPPM__in': ['Ketua LPPM', 'Anggota LPPM']}, related_name='pejabat_lppm', to='lppm.userprofile')),
                ('REVIEWER1', models.ManyToManyField(limit_choices_to={'KATEGORI': 'Dosen', 'REVIEWER': 'Ya'}, related_name='reviewer1', to='lppm.userprofile')),
                ('REVIEWER2', models.ManyToManyField(limit_choices_to={'KATEGORI': 'Dosen', 'REVIEWER': 'Ya'}, related_name='reviewer2', to='lppm.userprofile')),
                ('REVIEWER3', models.ManyToManyField(limit_choices_to={'KATEGORI': 'Dosen', 'REVIEWER': 'Ya'}, related_name='reviewer3', to='lppm.userprofile')),
            ],
            options={
                'verbose_name_plural': '03. Info Seminar',
            },
        ),
        migrations.AddField(
            model_name='pengajuanjadwal',
            name='NIDN_NPM',
            field=models.ManyToManyField(related_name='pengajuan_jadwal', to='lppm.userprofile'),
        ),
        migrations.AddField(
            model_name='berkaspengguna',
            name='NIDN_NPM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berkas_pengguna', to='lppm.userprofile'),
        ),
    ]
