# Generated by Django 4.1.4 on 2022-12-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bantuan',
            options={'verbose_name_plural': 'Bantuan'},
        ),
    ]
